# Generated by Django 2.2.10 on 2020-04-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200412_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=128, null=True)),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('data_saved', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
