# Generated by Django 2.2.10 on 2020-04-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_saveip'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveSignals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_changes', models.DateTimeField(auto_now=True)),
                ('type_changes', models.CharField(blank=True, max_length=128, null=True)),
                ('info_changes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
