# Generated by Django 2.2.10 on 2020-04-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_savesignals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savesignals',
            name='type_changes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Object created'), (3, 'Object edited'), (2, 'Object deleted')], max_length=128, null=True),
        ),
    ]
