# Generated by Django 2.2.10 on 2020-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200415_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savesignals',
            name='type_changes',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Object created'), (2, 'Object edited'), (3, 'Object deleted')], null=True),
        ),
    ]
